version: '3.8'


services:
  web: 
    image: nginx:latest
    ports:
      - 8080:80

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: rubee@123
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
